<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home', [
        "title" => "Home"
    ]);
});

Route::get('/about', function () {
    return view('about', [
        "title" => "About",
        "name" => "Sandhika Galih",
        "email" => "sandhikagalih@unpas.ac.id",
        "image" => "sandhika.jpg"
    ]);
});

Route::get('/blog', function () {
    $blog_posts = [
        [
            "title" => "Judul 1",
            "slug" => "judul-1",
            "author" => "Penulis 1",
            "body" => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae culpa optio debitis, quae corporis incidunt aspernatur ad officia pariatur ut! Impedit recusandae quasi quod aspernatur autem eaque modi hic vitae?"
        ],
        [
            "title" => "Judul 2",
            "slug" => "judul-2",
            "author" => "Penulis 2",
            "body" => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur odio consectetur praesentium, eos, autem rem voluptas cupiditate vitae velit officiis sint. Laudantium non sit, voluptates minima maiores asperiores dolor obcaecati. Reiciendis ab tempora, debitis deserunt iste omnis neque dolore pariatur repellendus nulla molestias nam vitae porro deleniti voluptatum aliquid eum eos soluta. Vel tempora quia nulla error obcaecati voluptate aperiam?
            Quae necessitatibus dignissimos odit ducimus amet! Sed nihil dolores dolore facilis ipsam veritatis excepturi, quisquam ab porro. Maxime quam laudantium voluptas eaque iusto, debitis explicabo inventore nam veniam quod officia. Cum soluta suscipit impedit, rem, sit voluptas reiciendis facilis aspernatur dignissimos sint deserunt fugit! Omnis voluptate, harum quibusdam reiciendis earum deserunt excepturi facilis unde, laborum quos fuga ducimus eaque nesciunt?
            Officiis nisi deleniti voluptatum a aliquam libero placeat, quos, error impedit dignissimos ratione itaque illum in! Facilis laborum ex in tenetur! Beatae nulla laboriosam provident modi. Inventore ullam odit beatae. Maiores voluptatem, nostrum deleniti molestiae assumenda sit nesciunt placeat perspiciatis veritatis repudiandae molestias, commodi maxime nihil delectus ad iure impedit! Harum non soluta voluptas accusantium, animi libero molestias recusandae asperiores.
            Recusandae labore cupiditate deleniti earum id consequatur voluptates, odit libero, ipsum nostrum asperiores sed repellat eaque minima nulla. Quia beatae soluta voluptatem blanditiis qui adipisci magni aliquid obcaecati culpa fugit! Ullam excepturi non sed rerum suscipit sunt, temporibus voluptates illum ea asperiores fugiat dignissimos totam eligendi. Natus ipsam assumenda aliquam itaque, eius maiores fugit facere debitis, beatae, corporis magnam doloremque?
            Libero minus eligendi mollitia excepturi ratione unde dignissimos quisquam beatae fugit modi reprehenderit praesentium nulla eos ipsa accusamus deserunt harum non esse, impedit voluptatibus, ut, voluptates iusto! Quaerat, magnam dolor. Excepturi nihil nulla quaerat inventore impedit soluta nam, ipsa, accusamus eaque ea ipsam quos sunt aperiam quisquam eius eum maiores deserunt? Quasi possimus ipsa soluta nam animi ut. Optio, odio?
            Vitae, consequatur eligendi. Consequatur, quos magnam molestias nobis id magni quia facere inventore dolorem iste animi libero porro perspiciatis numquam tempora doloremque sed architecto? Eum, ex. Iure suscipit sint eos? Facere, architecto? Neque eos sint voluptate omnis, qui iusto corrupti consectetur necessitatibus, ullam velit impedit blanditiis numquam! Nihil maiores porro, consequuntur sed veniam sint quod rerum ratione facilis, vel quibusdam?
            Excepturi ullam dignissimos cumque omnis facere. Ad, fugit doloribus nam aperiam odit officiis obcaecati asperiores reiciendis necessitatibus. Animi et at vitae nisi quibusdam quam numquam vel voluptates, modi, ullam nihil! Blanditiis, quo debitis. Temporibus illum quo natus tenetur quaerat vitae asperiores! Saepe eligendi quasi atque suscipit consequatur similique facere aspernatur laborum illo enim, provident, voluptatibus sequi possimus tenetur recusandae quisquam!
            Recusandae voluptas culpa ipsam? Voluptatem et ipsam earum omnis nostrum enim qui hic quia excepturi explicabo! Quisquam, omnis minima eaque ullam iusto voluptate fugiat velit molestias saepe rem reiciendis nostrum. Atque illum exercitationem doloribus laborum officia recusandae dicta aliquam iure nulla quibusdam animi minima autem minus rerum, ab vitae et corporis maiores qui soluta? Ratione repellendus nobis eos recusandae provident?
            Dignissimos tempore itaque ullam. Dolore officiis veniam quae tempore id voluptates ullam in quos et, modi doloremque blanditiis assumenda vero aperiam, saepe ad? Quasi expedita molestiae, earum praesentium eum perspiciatis. Non, possimus. Odit, obcaecati quibusdam suscipit sunt minima ab. Quas, nemo sint? Ipsum, consequatur fugit. Id temporibus dicta nisi cum dolor iste voluptates deleniti est pariatur, expedita sequi atque. Quam.
            Esse in vitae, laborum dicta cupiditate possimus eligendi eius vero perferendis laudantium rem ut mollitia sequi ullam ab reiciendis est nemo, non, porro veritatis alias nulla deserunt odio reprehenderit. Eligendi. Sequi iste accusamus praesentium. Voluptate quibusdam unde laudantium possimus nemo, optio dignissimos officia ad, voluptas labore quis. Amet fuga animi ullam quas! Nobis porro necessitatibus dolor officia veniam quia officiis.
            Vero, nisi. Dolorum, harum! Aliquid ducimus expedita ex quas magnam, in harum, rerum necessitatibus, nesciunt fugiat facere modi molestias! Fugit id est quaerat culpa suscipit laudantium praesentium assumenda consectetur nisi. Harum doloremque quae tempora saepe ex distinctio, at dignissimos voluptatem vero amet totam reiciendis repudiandae atque quibusdam pariatur odit quam dolor iusto, enim fugiat labore laboriosam? Ipsum accusamus omnis eos.
            Minima magnam dicta tempora, exercitationem vitae, facere itaque facilis suscipit architecto quam tempore! Dignissimos excepturi fugit pariatur perspiciatis necessitatibus, consequatur consectetur, voluptate eaque eius quas architecto veniam animi aspernatur suscipit? Quia dolore voluptatum libero, hic velit possimus optio aperiam cupiditate! Sed veniam nobis qui ullam ipsam minus, inventore facilis nam eius dolores eum magnam fugit, est, molestiae eligendi beatae optio.
            Aliquam deserunt repellat sequi nam reiciendis libero earum? Vero sed dignissimos dicta harum sit. Obcaecati sequi vitae rem porro. Totam voluptate molestias provident. Officia doloremque, blanditiis obcaecati molestias illo cupiditate! Id asperiores architecto fugiat suscipit dolores veritatis sunt unde. Accusantium fuga dolore quos, debitis, facere voluptas, enim a culpa doloribus hic obcaecati asperiores. Quas voluptatum consequatur aut sit, nesciunt distinctio.
            Voluptatibus fugit laudantium cum reprehenderit adipisci neque modi placeat explicabo, blanditiis mollitia provident voluptas dolore, rerum minima culpa sapiente earum obcaecati aliquam asperiores. Earum dolores esse similique at reiciendis architecto. Adipisci alias esse recusandae velit, provident sapiente! Nulla voluptatum optio debitis nihil autem eum maiores eveniet non dolor dignissimos enim quisquam libero cum omnis excepturi neque, voluptatem, quaerat praesentium perspiciatis.
            Amet tenetur sed voluptatum est voluptatem, distinctio facilis repellendus nulla magni, dolorum beatae labore. Veniam reprehenderit, incidunt, ipsam eligendi officia perferendis nostrum modi maxime, omnis dolorem itaque asperiores sunt sed? Quaerat pariatur beatae quas et reprehenderit asperiores ipsam natus, repellat provident eum eius animi, expedita fuga tenetur facere! Exercitationem voluptate explicabo cumque, iusto atque eveniet laudantium odio optio debitis iure.
            Libero facilis tenetur quisquam at, earum quis dolorum delectus voluptatum maxime optio adipisci temporibus atque? Sapiente voluptates debitis totam magni qui aut odit, iure fugit adipisci, sunt nam, nesciunt sed? Accusamus totam perspiciatis dicta quia minus, mollitia temporibus harum, nam doloribus, quod soluta quos suscipit velit laudantium blanditiis qui amet id quasi distinctio quis fugit at culpa labore. Quibusdam, doloribus.
            Deserunt omnis molestias voluptatibus vero culpa facere minima accusantium, ipsam sequi ipsum porro. Aliquid, sit perferendis beatae, dolores ea, et nisi nemo nihil molestias dolor nam earum reprehenderit aspernatur vero? Quis vitae repudiandae unde totam aspernatur voluptates repellat dolorum doloribus? Delectus explicabo excepturi blanditiis iure nulla, cupiditate eaque nam, voluptatum distinctio doloribus consectetur ad aut eveniet sed neque, rerum reprehenderit.
            In beatae aliquam omnis vero, provident nemo eligendi impedit aut ipsa rem animi exercitationem optio. Dolor incidunt qui esse eos in voluptatibus, distinctio, illo eum totam ratione ipsa sit? Officiis? Deserunt, expedita! Error facilis maxime nobis architecto modi reprehenderit at ipsum laudantium quae! Reprehenderit dolorem praesentium rem! Vitae maiores quisquam necessitatibus? Fugiat ab sed, veritatis debitis ullam tempora recusandae suscipit?
            Beatae cum sequi iure tenetur soluta harum assumenda iste totam accusamus laboriosam esse veniam, ut quidem earum officia nesciunt illo quisquam eaque temporibus. Doloribus sunt excepturi perspiciatis quidem! Consequuntur, nostrum! Dolores incidunt magni, qui id fugit consectetur nam. Possimus, odit id molestiae dicta exercitationem corporis. Omnis nobis itaque rem officia porro, sapiente autem repellendus magni quaerat similique unde deleniti nisi?
            Ratione et ex expedita labore aliquam ad? Hic natus facere odio sit nobis. Eius quaerat repudiandae ullam, corrupti corporis commodi maiores alias quis veniam non quisquam saepe libero quos amet? Delectus quasi temporibus odit porro repellat ea odio, tempore officiis. Dignissimos iusto, eveniet soluta velit magni tempora? Eveniet nulla asperiores voluptatum voluptatibus, esse maxime quia, molestiae et facere nobis deleniti!
            Nihil error velit vel consequatur dolorem tempore est praesentium itaque, perferendis natus. Consequatur minus assumenda veniam voluptate cupiditate, a laborum, commodi ullam earum atque iusto voluptatem quia nisi quam pariatur! Officiis, doloremque possimus perferendis voluptatibus laborum qui veritatis debitis natus, rerum aut ullam dolores sunt eveniet maiores optio commodi, cupiditate odit perspiciatis veniam tempora libero doloribus! Maiores ratione adipisci atque.
            Mollitia quidem itaque earum maxime sapiente, inventore aliquid fuga placeat totam ipsam reiciendis. Sequi consequatur quae, eaque, sunt laudantium unde vero expedita porro fugit corporis molestias iste perferendis voluptate explicabo. Ipsam facere quasi animi illum iusto sed officiis, veniam eligendi, aut ratione quis obcaecati porro vitae! Laborum assumenda quibusdam, porro dolorem earum facere ipsum, veniam itaque suscipit, nisi unde autem.
            Quae excepturi unde ipsam ea minus reiciendis. Dolore qui possimus explicabo ut non unde voluptatum iusto neque quasi eius, temporibus excepturi ex eaque soluta dolor maxime omnis accusamus itaque totam! Culpa quaerat voluptatum molestias eveniet harum saepe perferendis adipisci asperiores magnam reiciendis voluptatem, aliquid, aperiam dicta excepturi odio dolore assumenda. Quasi debitis mollitia odio facilis accusamus corrupti explicabo id nihil!
            Fugit voluptates iure ex tenetur sequi debitis reprehenderit aspernatur! Minus consequuntur assumenda commodi eaque et tenetur officiis, necessitatibus eveniet, animi, error impedit totam? Fugiat aut placeat soluta, excepturi temporibus quidem? Alias, amet? Cumque sequi beatae nobis. Tempore, tenetur pariatur velit distinctio et, laborum assumenda esse rem laboriosam provident eos. Voluptatem quas eius officia tempore obcaecati et quisquam nihil aliquid unde?
            Voluptatem sit sed aperiam magni, quae aspernatur sapiente sequi, recusandae officiis quibusdam ut molestias nulla est? Maxime perferendis autem et omnis explicabo maiores distinctio accusantium, enim reiciendis fugit temporibus incidunt! Natus culpa hic atque suscipit ipsum nam nobis at minus vitae dignissimos repudiandae sit nulla voluptatum, adipisci expedita vero commodi esse. Suscipit mollitia ab aspernatur corrupti. Magnam obcaecati assumenda nisi?
            Debitis quis, aperiam nam sint obcaecati distinctio quidem hic, deleniti est qui illum voluptatem fuga incidunt iste quod! Temporibus cupiditate officia fuga unde sapiente ipsam repudiandae quos quod quia. Aut. Repudiandae ullam placeat esse, debitis sint recusandae cumque fuga nam in quibusdam ex corrupti illo fugit voluptas accusamus delectus nulla aut aliquid consequatur libero? Ducimus commodi deserunt suscipit dolorum cum!
            Voluptatibus qui nulla porro cumque, nisi quisquam ipsa? Consequatur nihil non neque vero ullam atque officiis voluptatum eius quaerat sequi saepe animi, ex alias harum dolorem eum quia soluta quidem. Consequatur dolor natus officiis alias quibusdam veritatis amet impedit animi adipisci aspernatur aliquam illum doloremque, suscipit ea repellendus velit aliquid eius qui deleniti dolore molestias ullam? Repudiandae alias voluptatibus ipsum.
            Aliquam ex nesciunt delectus eveniet harum animi, consequatur nostrum quibusdam magni fugiat cum quas esse placeat eligendi commodi assumenda asperiores quasi nam neque voluptatibus error sequi debitis optio natus. Officiis. Expedita vel doloremque impedit exercitationem reiciendis eum inventore hic architecto nam amet, provident incidunt illum, est labore alias modi suscipit magnam vero iste voluptatum. Obcaecati nostrum sit in laboriosam possimus.
            Repellendus unde aperiam cupiditate repudiandae sunt veniam tempore! Nesciunt, dignissimos. Nobis nemo mollitia fugiat sint, est possimus quo fuga quasi, ab commodi natus reiciendis autem? Necessitatibus vitae repellendus repellat ipsa. Incidunt fugit aut voluptatum nam beatae impedit nemo explicabo rerum dicta non tenetur atque voluptas soluta quam, inventore quo vel ea deleniti adipisci sint nisi, quod animi dolore. Odit, repellat.
            Ad eum impedit quasi fuga quibusdam minus earum cupiditate perferendis inventore vero esse culpa iure in harum possimus, veniam ratione reiciendis quidem sit? Amet a excepturi impedit animi alias natus. Cumque quae quas dicta tempora nesciunt quidem, beatae ipsam porro, fugit nemo sit? Expedita doloremque saepe voluptatum minima voluptate eaque blanditiis ut eligendi cupiditate aperiam veniam pariatur, quae officia exercitationem!
            Nobis, iste dicta exercitationem repellat illo id quas hic. Totam inventore excepturi aliquid distinctio repudiandae qui placeat. Incidunt, soluta esse ipsa itaque veritatis harum aut doloremque, optio a, est cupiditate? Minima beatae eum excepturi neque, aut aliquam quod fuga veniam, nesciunt, molestiae dolorem cumque. Cupiditate officiis, aliquam quas illum laborum culpa error modi quae non soluta dolores repudiandae, ipsam veritatis?
            Similique, accusantium vel temporibus dicta blanditiis quibusdam repellat ex tempora reprehenderit neque illo architecto deserunt? Suscipit, tempora eius recusandae magnam, error quis eos ad ipsum, eum quidem facere minus itaque. Vel voluptatum consequuntur earum quas ut delectus, animi fugit esse, nobis nam velit ad natus consequatur dicta rem accusamus recusandae provident? Quos nostrum non eum, blanditiis et veritatis id provident.
            Soluta rerum adipisci fugiat laboriosam molestias nisi pariatur mollitia, eveniet fuga repellat vel ipsam reprehenderit sapiente a culpa. Hic impedit natus maxime beatae, mollitia necessitatibus? Numquam, molestias! Eum, eos laudantium. Non dolorem commodi expedita veritatis reprehenderit aperiam quaerat maxime doloremque pariatur beatae, eveniet ipsam! Laboriosam illum ullam et amet repudiandae officiis? Quod deserunt ex iure iste incidunt ab eos consequuntur!
            Fuga facere quam at quibusdam eligendi aut consequuntur maiores consectetur sequi dolore nihil, natus veniam iure sunt enim neque. Qui temporibus vero et quasi maiores fugit soluta doloribus quae! Molestias. Similique possimus sequi blanditiis corrupti deserunt ut illo cum distinctio, minus architecto dolorem tempore libero minima amet porro, assumenda nulla beatae alias maiores eligendi exercitationem reprehenderit. Atque nobis voluptatibus numquam.
            Qui officiis fugiat accusamus illum, aut nam reprehenderit iure, quas aspernatur laudantium labore voluptates unde corrupti? Esse laboriosam officia, quia et reprehenderit inventore, magnam obcaecati qui iure eos aperiam suscipit? Adipisci corrupti quas repellat earum voluptas dicta eveniet at amet saepe error? Vel repellendus natus animi ex dicta ipsa, totam accusamus molestias quam pariatur esse eligendi error minima ut voluptatibus!
            Deserunt dolorem modi possimus blanditiis magni vitae soluta repudiandae molestiae, aspernatur eius velit quasi nulla iusto ab quam optio eaque mollitia iure enim, aut consectetur id? Ipsum suscipit et itaque. Adipisci aspernatur sed aliquid quibusdam voluptate illo dolorum, doloremque quia dignissimos earum laborum, delectus aliquam rem nostrum laboriosam. Accusantium eveniet ipsa velit a itaque eos, reiciendis aperiam culpa quis consequatur.
            Ducimus, omnis ab amet vitae harum expedita fugit atque maiores ex totam reiciendis eius iste obcaecati. Tempora, dolor culpa. Nesciunt, sequi modi? Error natus repudiandae sapiente odio reiciendis et perferendis. Doloremque facilis unde soluta nisi praesentium, possimus magnam consectetur, autem, earum quaerat hic tempore. Laudantium distinctio, at omnis nulla, quam atque soluta iure totam facilis eius praesentium quia sit in.
            Nemo doloremque placeat fugit quae! Deleniti hic impedit distinctio nostrum eum ipsa similique dolorum, accusantium optio velit. Odio eaque veritatis tempora corrupti sed, pariatur officiis, fugit, harum eum voluptates quae! Commodi magni impedit et explicabo voluptatum aperiam soluta eos. Dignissimos sed dolorum ab exercitationem nihil, minus aliquid cumque? Magnam voluptas distinctio neque facilis doloremque in enim iusto aliquid totam asperiores.
            Modi pariatur sequi ea ratione quisquam autem itaque, voluptate, omnis quidem in eligendi quas totam sapiente quam vero eius ipsum dignissimos incidunt corrupti perferendis quaerat enim aspernatur delectus! Dolore, delectus. Eligendi eius inventore nulla, amet nesciunt optio corporis fugiat! Possimus, repellendus aperiam exercitationem, deserunt culpa vero voluptatem, eum qui maxime quod sequi fugit. Quidem odio, doloremque totam officia consequuntur non!
            Nostrum, doloremque ipsa. Saepe sequi eligendi obcaecati fugiat tenetur? Excepturi sapiente fuga odio corrupti blanditiis atque, doloribus mollitia vitae eveniet perspiciatis voluptates quia ab sint sunt quasi deleniti dolorum ipsa. Veritatis, eligendi illo? Ipsum aperiam numquam sequi animi tempora esse doloribus sed aut, a quia! In repellat nulla sed magni repudiandae quasi blanditiis sequi architecto dignissimos. Vero illum natus est!
            Dignissimos velit eius nostrum ab voluptates. Sed laudantium eius exercitationem iusto. Accusantium voluptates ratione expedita id pariatur qui quis iusto eos nesciunt suscipit quam, vitae minus animi quod temporibus maxime! Nostrum corporis suscipit repellendus quo, ut nobis, corrupti accusantium quia expedita, quod quam? Deserunt maxime atque ipsa? Omnis ad nesciunt culpa ut, commodi fuga repudiandae nobis harum eaque, animi et.
            Molestiae id commodi dolor rem quas provident ipsam culpa totam reprehenderit aperiam. Magni, voluptatem? Rem minima, deserunt provident, eum nihil adipisci quae voluptate quibusdam perferendis, velit blanditiis incidunt inve necessitatibus. Quo blanditiis voluptas sit! Similique, dignissimos nesciunt aliquid cumque magni veniam voluptates explicabo voluptatum ullam beatae fuga. Incidunt blanditiis veritatis amet. Hic laudantium asperiores corporis, blanditiis assumenda eos quia illum.
            Deleniti temporibus voluptates sequi dolorem asperiores. Repellat voluptas doloribus explicabo nam, aperiam quos quibusdam labore non ipsa voluptatem et, natus nobis pariatur eaque eos id dolor nulla unde optio porro? Quisquam blanditiis ea, aperiam pariatur quaerat placeat labore, debitis deserunt sequi est quasi maiores quidem ipsam laboriosam atque nobis veniam tempora dolor exercitationem temporibus! Voluptas consequuntur eum repellat commodi adipisci?
            At sunt mollitia aliquid impedit ipsam sit velit rerum necessitatibus excepturi quibusdam! Ducimus ipsam quam minima possimus, at inventore minus. Dolorem, eius numquam? Id distinctio consectetur, similique voluptatibus iure odio. Ad dolores ducimus quaerat beatae! Fugiat minus tenetur, distinctio placeat tempore voluptatem, maxime est at, quasi illum harum natus quo iusto error corporis fuga veritatis cumque! Cumque commodi nihil sapiente?
            Ullam, blanditiis perferendis? Cum fuga suscipit optio. Aperiam laborum minima repellat, doloribus placeat atque officia quos dolore ut a molestiae illum, corrupti minus cumque alias reprehenderit? Minus explicabo magnam quod. Perspiciatis, soluta cum velit fuga corrupti obcaecati atque aut odit blanditiis consequuntur eius, culpa optio debitis eum! Ex, ipsam repudiandae. Qui eius porro odio sit omnis quae ut? Iure, distinctio.
            Dolore omnis, saepe totam voluptate eius doloribus magnam cumque et exercitationem perspiciatis vero neque ipsam, voluptatem dolorem rem odio quae fuga sequi deserunt! Dolorem ipsam mollitia at quas fugit et! Voluptates, assumenda. Ea facilis, sapiente, assumenda doloribus sed fugiat quis eaque amet labore voluptatem fugit reiciendis asperiores. Aperiam, voluptatibus? Repellendus aspernatur corporis earum neque modi labore incidunt esse similique nihil.
            Accusantium itaque suscipit nisi ut eveniet, quisquam tempore, culpa necessitatibus facere iste quo. Adipisci possimus similique at, accusantium tempore dolore incidunt explicabo assumenda eaque, quaerat et porro cumque repellendus distinctio! Sapiente quaerat ad aut, nisi error quis laboriosam! Eum sed sapiente neque rerum, suscipit enim deserunt quisquam debitis ipsa inventore in necessitatibus, quaerat dolor tenetur consequuntur nulla temporibus laboriosam soluta?
            Fugiat quod, ex vel architecto maxime soluta dolores eveniet molestias magnam? Iusto perferendis illum, quas corporis ad cumque tempore magni accusantium voluptate minus necessitatibus eum aperiam? Excepturi quisquam cumque minima? Temporibus repudiandae perferendis ullam praesentium dignissimos maxime dolore non harum dolores ducimus, delectus amet accusamus dolor eum culpa voluptas dicta pariatur illo eveniet dolorum officia. Maxime iste commodi nisi iure!
            Vitae magnam aliquid illo cupiditate architecto asperiores enim! Quis, qui atque eveniet voluptates sint, dolor excepturi natus pariatur at a maxime accusamus repellendus assumenda commodi tempora maiores eligendi, deleniti itaque. Voluptatibus atque exercitationem nesciunt, numquam, recusandae reprehenderit impedit nostrum, vero distinctio corporis modi? Ipsum alias blanditiis est itaque autem, odio magni. Earum, animi a! Doloremque nihil voluptatibus delectus aut sint?
            Vero obcaecati nemo in quae nobis. Fugiat delectus aut veniam at eius, saepe cupiditate magni in velit sed ad neque. Quibusdam nihil consectetur dignissimos, aliquid quisquam suscipit quae autem error? Rem repudiandae quia aliquid, doloribus voluptatibus voluptas, dolore culpa consectetur esse vero deleniti numquam harum ad exercitationem distinctio voluptatem. Laboriosam itaque tempore iure voluptas autem dolorum minus perferendis fugit sunt?"
        ]
    ];

    return view('posts', [
        "title" => "Posts",
        "posts" => $blog_posts
    ]);
});

Route::get('post/{slug}', function ($slug) {
    $blog_posts = [
        [
            "title" => "Judul 1",
            "slug" => "judul-1",
            "author" => "Penulis 1",
            "body" => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae culpa optio debitis, quae corporis incidunt aspernatur ad officia pariatur ut! Impedit recusandae quasi quod aspernatur autem eaque modi hic vitae?"
        ],
        [
            "title" => "Judul 2",
            "slug" => "judul-2",
            "author" => "Penulis 2",
            "body" => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur odio consectetur praesentium, eos, autem rem voluptas cupiditate vitae velit officiis sint. Laudantium non sit, voluptates minima maiores asperiores dolor obcaecati. Reiciendis ab tempora, debitis deserunt iste omnis neque dolore pariatur repellendus nulla molestias nam vitae porro deleniti voluptatum aliquid eum eos soluta. Vel tempora quia nulla error obcaecati voluptate aperiam?
            Quae necessitatibus dignissimos odit ducimus amet! Sed nihil dolores dolore facilis ipsam veritatis excepturi, quisquam ab porro. Maxime quam laudantium voluptas eaque iusto, debitis explicabo inventore nam veniam quod officia. Cum soluta suscipit impedit, rem, sit voluptas reiciendis facilis aspernatur dignissimos sint deserunt fugit! Omnis voluptate, harum quibusdam reiciendis earum deserunt excepturi facilis unde, laborum quos fuga ducimus eaque nesciunt?
            Officiis nisi deleniti voluptatum a aliquam libero placeat, quos, error impedit dignissimos ratione itaque illum in! Facilis laborum ex in tenetur! Beatae nulla laboriosam provident modi. Inventore ullam odit beatae. Maiores voluptatem, nostrum deleniti molestiae assumenda sit nesciunt placeat perspiciatis veritatis repudiandae molestias, commodi maxime nihil delectus ad iure impedit! Harum non soluta voluptas accusantium, animi libero molestias recusandae asperiores.
            Recusandae labore cupiditate deleniti earum id consequatur voluptates, odit libero, ipsum nostrum asperiores sed repellat eaque minima nulla. Quia beatae soluta voluptatem blanditiis qui adipisci magni aliquid obcaecati culpa fugit! Ullam excepturi non sed rerum suscipit sunt, temporibus voluptates illum ea asperiores fugiat dignissimos totam eligendi. Natus ipsam assumenda aliquam itaque, eius maiores fugit facere debitis, beatae, corporis magnam doloremque?
            Libero minus eligendi mollitia excepturi ratione unde dignissimos quisquam beatae fugit modi reprehenderit praesentium nulla eos ipsa accusamus deserunt harum non esse, impedit voluptatibus, ut, voluptates iusto! Quaerat, magnam dolor. Excepturi nihil nulla quaerat inventore impedit soluta nam, ipsa, accusamus eaque ea ipsam quos sunt aperiam quisquam eius eum maiores deserunt? Quasi possimus ipsa soluta nam animi ut. Optio, odio?
            Vitae, consequatur eligendi. Consequatur, quos magnam molestias nobis id magni quia facere inventore dolorem iste animi libero porro perspiciatis numquam tempora doloremque sed architecto? Eum, ex. Iure suscipit sint eos? Facere, architecto? Neque eos sint voluptate omnis, qui iusto corrupti consectetur necessitatibus, ullam velit impedit blanditiis numquam! Nihil maiores porro, consequuntur sed veniam sint quod rerum ratione facilis, vel quibusdam?
            Excepturi ullam dignissimos cumque omnis facere. Ad, fugit doloribus nam aperiam odit officiis obcaecati asperiores reiciendis necessitatibus. Animi et at vitae nisi quibusdam quam numquam vel voluptates, modi, ullam nihil! Blanditiis, quo debitis. Temporibus illum quo natus tenetur quaerat vitae asperiores! Saepe eligendi quasi atque suscipit consequatur similique facere aspernatur laborum illo enim, provident, voluptatibus sequi possimus tenetur recusandae quisquam!
            Recusandae voluptas culpa ipsam? Voluptatem et ipsam earum omnis nostrum enim qui hic quia excepturi explicabo! Quisquam, omnis minima eaque ullam iusto voluptate fugiat velit molestias saepe rem reiciendis nostrum. Atque illum exercitationem doloribus laborum officia recusandae dicta aliquam iure nulla quibusdam animi minima autem minus rerum, ab vitae et corporis maiores qui soluta? Ratione repellendus nobis eos recusandae provident?
            Dignissimos tempore itaque ullam. Dolore officiis veniam quae tempore id voluptates ullam in quos et, modi doloremque blanditiis assumenda vero aperiam, saepe ad? Quasi expedita molestiae, earum praesentium eum perspiciatis. Non, possimus. Odit, obcaecati quibusdam suscipit sunt minima ab. Quas, nemo sint? Ipsum, consequatur fugit. Id temporibus dicta nisi cum dolor iste voluptates deleniti est pariatur, expedita sequi atque. Quam.
            Esse in vitae, laborum dicta cupiditate possimus eligendi eius vero perferendis laudantium rem ut mollitia sequi ullam ab reiciendis est nemo, non, porro veritatis alias nulla deserunt odio reprehenderit. Eligendi. Sequi iste accusamus praesentium. Voluptate quibusdam unde laudantium possimus nemo, optio dignissimos officia ad, voluptas labore quis. Amet fuga animi ullam quas! Nobis porro necessitatibus dolor officia veniam quia officiis.
            Vero, nisi. Dolorum, harum! Aliquid ducimus expedita ex quas magnam, in harum, rerum necessitatibus, nesciunt fugiat facere modi molestias! Fugit id est quaerat culpa suscipit laudantium praesentium assumenda consectetur nisi. Harum doloremque quae tempora saepe ex distinctio, at dignissimos voluptatem vero amet totam reiciendis repudiandae atque quibusdam pariatur odit quam dolor iusto, enim fugiat labore laboriosam? Ipsum accusamus omnis eos.
            Minima magnam dicta tempora, exercitationem vitae, facere itaque facilis suscipit architecto quam tempore! Dignissimos excepturi fugit pariatur perspiciatis necessitatibus, consequatur consectetur, voluptate eaque eius quas architecto veniam animi aspernatur suscipit? Quia dolore voluptatum libero, hic velit possimus optio aperiam cupiditate! Sed veniam nobis qui ullam ipsam minus, inventore facilis nam eius dolores eum magnam fugit, est, molestiae eligendi beatae optio.
            Aliquam deserunt repellat sequi nam reiciendis libero earum? Vero sed dignissimos dicta harum sit. Obcaecati sequi vitae rem porro. Totam voluptate molestias provident. Officia doloremque, blanditiis obcaecati molestias illo cupiditate! Id asperiores architecto fugiat suscipit dolores veritatis sunt unde. Accusantium fuga dolore quos, debitis, facere voluptas, enim a culpa doloribus hic obcaecati asperiores. Quas voluptatum consequatur aut sit, nesciunt distinctio.
            Voluptatibus fugit laudantium cum reprehenderit adipisci neque modi placeat explicabo, blanditiis mollitia provident voluptas dolore, rerum minima culpa sapiente earum obcaecati aliquam asperiores. Earum dolores esse similique at reiciendis architecto. Adipisci alias esse recusandae velit, provident sapiente! Nulla voluptatum optio debitis nihil autem eum maiores eveniet non dolor dignissimos enim quisquam libero cum omnis excepturi neque, voluptatem, quaerat praesentium perspiciatis.
            Amet tenetur sed voluptatum est voluptatem, distinctio facilis repellendus nulla magni, dolorum beatae labore. Veniam reprehenderit, incidunt, ipsam eligendi officia perferendis nostrum modi maxime, omnis dolorem itaque asperiores sunt sed? Quaerat pariatur beatae quas et reprehenderit asperiores ipsam natus, repellat provident eum eius animi, expedita fuga tenetur facere! Exercitationem voluptate explicabo cumque, iusto atque eveniet laudantium odio optio debitis iure.
            Libero facilis tenetur quisquam at, earum quis dolorum delectus voluptatum maxime optio adipisci temporibus atque? Sapiente voluptates debitis totam magni qui aut odit, iure fugit adipisci, sunt nam, nesciunt sed? Accusamus totam perspiciatis dicta quia minus, mollitia temporibus harum, nam doloribus, quod soluta quos suscipit velit laudantium blanditiis qui amet id quasi distinctio quis fugit at culpa labore. Quibusdam, doloribus.
            Deserunt omnis molestias voluptatibus vero culpa facere minima accusantium, ipsam sequi ipsum porro. Aliquid, sit perferendis beatae, dolores ea, et nisi nemo nihil molestias dolor nam earum reprehenderit aspernatur vero? Quis vitae repudiandae unde totam aspernatur voluptates repellat dolorum doloribus? Delectus explicabo excepturi blanditiis iure nulla, cupiditate eaque nam, voluptatum distinctio doloribus consectetur ad aut eveniet sed neque, rerum reprehenderit.
            In beatae aliquam omnis vero, provident nemo eligendi impedit aut ipsa rem animi exercitationem optio. Dolor incidunt qui esse eos in voluptatibus, distinctio, illo eum totam ratione ipsa sit? Officiis? Deserunt, expedita! Error facilis maxime nobis architecto modi reprehenderit at ipsum laudantium quae! Reprehenderit dolorem praesentium rem! Vitae maiores quisquam necessitatibus? Fugiat ab sed, veritatis debitis ullam tempora recusandae suscipit?
            Beatae cum sequi iure tenetur soluta harum assumenda iste totam accusamus laboriosam esse veniam, ut quidem earum officia nesciunt illo quisquam eaque temporibus. Doloribus sunt excepturi perspiciatis quidem! Consequuntur, nostrum! Dolores incidunt magni, qui id fugit consectetur nam. Possimus, odit id molestiae dicta exercitationem corporis. Omnis nobis itaque rem officia porro, sapiente autem repellendus magni quaerat similique unde deleniti nisi?
            Ratione et ex expedita labore aliquam ad? Hic natus facere odio sit nobis. Eius quaerat repudiandae ullam, corrupti corporis commodi maiores alias quis veniam non quisquam saepe libero quos amet? Delectus quasi temporibus odit porro repellat ea odio, tempore officiis. Dignissimos iusto, eveniet soluta velit magni tempora? Eveniet nulla asperiores voluptatum voluptatibus, esse maxime quia, molestiae et facere nobis deleniti!
            Nihil error velit vel consequatur dolorem tempore est praesentium itaque, perferendis natus. Consequatur minus assumenda veniam voluptate cupiditate, a laborum, commodi ullam earum atque iusto voluptatem quia nisi quam pariatur! Officiis, doloremque possimus perferendis voluptatibus laborum qui veritatis debitis natus, rerum aut ullam dolores sunt eveniet maiores optio commodi, cupiditate odit perspiciatis veniam tempora libero doloribus! Maiores ratione adipisci atque.
            Mollitia quidem itaque earum maxime sapiente, inventore aliquid fuga placeat totam ipsam reiciendis. Sequi consequatur quae, eaque, sunt laudantium unde vero expedita porro fugit corporis molestias iste perferendis voluptate explicabo. Ipsam facere quasi animi illum iusto sed officiis, veniam eligendi, aut ratione quis obcaecati porro vitae! Laborum assumenda quibusdam, porro dolorem earum facere ipsum, veniam itaque suscipit, nisi unde autem.
            Quae excepturi unde ipsam ea minus reiciendis. Dolore qui possimus explicabo ut non unde voluptatum iusto neque quasi eius, temporibus excepturi ex eaque soluta dolor maxime omnis accusamus itaque totam! Culpa quaerat voluptatum molestias eveniet harum saepe perferendis adipisci asperiores magnam reiciendis voluptatem, aliquid, aperiam dicta excepturi odio dolore assumenda. Quasi debitis mollitia odio facilis accusamus corrupti explicabo id nihil!
            Fugit voluptates iure ex tenetur sequi debitis reprehenderit aspernatur! Minus consequuntur assumenda commodi eaque et tenetur officiis, necessitatibus eveniet, animi, error impedit totam? Fugiat aut placeat soluta, excepturi temporibus quidem? Alias, amet? Cumque sequi beatae nobis. Tempore, tenetur pariatur velit distinctio et, laborum assumenda esse rem laboriosam provident eos. Voluptatem quas eius officia tempore obcaecati et quisquam nihil aliquid unde?
            Voluptatem sit sed aperiam magni, quae aspernatur sapiente sequi, recusandae officiis quibusdam ut molestias nulla est? Maxime perferendis autem et omnis explicabo maiores distinctio accusantium, enim reiciendis fugit temporibus incidunt! Natus culpa hic atque suscipit ipsum nam nobis at minus vitae dignissimos repudiandae sit nulla voluptatum, adipisci expedita vero commodi esse. Suscipit mollitia ab aspernatur corrupti. Magnam obcaecati assumenda nisi?
            Debitis quis, aperiam nam sint obcaecati distinctio quidem hic, deleniti est qui illum voluptatem fuga incidunt iste quod! Temporibus cupiditate officia fuga unde sapiente ipsam repudiandae quos quod quia. Aut. Repudiandae ullam placeat esse, debitis sint recusandae cumque fuga nam in quibusdam ex corrupti illo fugit voluptas accusamus delectus nulla aut aliquid consequatur libero? Ducimus commodi deserunt suscipit dolorum cum!
            Voluptatibus qui nulla porro cumque, nisi quisquam ipsa? Consequatur nihil non neque vero ullam atque officiis voluptatum eius quaerat sequi saepe animi, ex alias harum dolorem eum quia soluta quidem. Consequatur dolor natus officiis alias quibusdam veritatis amet impedit animi adipisci aspernatur aliquam illum doloremque, suscipit ea repellendus velit aliquid eius qui deleniti dolore molestias ullam? Repudiandae alias voluptatibus ipsum.
            Aliquam ex nesciunt delectus eveniet harum animi, consequatur nostrum quibusdam magni fugiat cum quas esse placeat eligendi commodi assumenda asperiores quasi nam neque voluptatibus error sequi debitis optio natus. Officiis. Expedita vel doloremque impedit exercitationem reiciendis eum inventore hic architecto nam amet, provident incidunt illum, est labore alias modi suscipit magnam vero iste voluptatum. Obcaecati nostrum sit in laboriosam possimus.
            Repellendus unde aperiam cupiditate repudiandae sunt veniam tempore! Nesciunt, dignissimos. Nobis nemo mollitia fugiat sint, est possimus quo fuga quasi, ab commodi natus reiciendis autem? Necessitatibus vitae repellendus repellat ipsa. Incidunt fugit aut voluptatum nam beatae impedit nemo explicabo rerum dicta non tenetur atque voluptas soluta quam, inventore quo vel ea deleniti adipisci sint nisi, quod animi dolore. Odit, repellat.
            Ad eum impedit quasi fuga quibusdam minus earum cupiditate perferendis inventore vero esse culpa iure in harum possimus, veniam ratione reiciendis quidem sit? Amet a excepturi impedit animi alias natus. Cumque quae quas dicta tempora nesciunt quidem, beatae ipsam porro, fugit nemo sit? Expedita doloremque saepe voluptatum minima voluptate eaque blanditiis ut eligendi cupiditate aperiam veniam pariatur, quae officia exercitationem!
            Nobis, iste dicta exercitationem repellat illo id quas hic. Totam inventore excepturi aliquid distinctio repudiandae qui placeat. Incidunt, soluta esse ipsa itaque veritatis harum aut doloremque, optio a, est cupiditate? Minima beatae eum excepturi neque, aut aliquam quod fuga veniam, nesciunt, molestiae dolorem cumque. Cupiditate officiis, aliquam quas illum laborum culpa error modi quae non soluta dolores repudiandae, ipsam veritatis?
            Similique, accusantium vel temporibus dicta blanditiis quibusdam repellat ex tempora reprehenderit neque illo architecto deserunt? Suscipit, tempora eius recusandae magnam, error quis eos ad ipsum, eum quidem facere minus itaque. Vel voluptatum consequuntur earum quas ut delectus, animi fugit esse, nobis nam velit ad natus consequatur dicta rem accusamus recusandae provident? Quos nostrum non eum, blanditiis et veritatis id provident.
            Soluta rerum adipisci fugiat laboriosam molestias nisi pariatur mollitia, eveniet fuga repellat vel ipsam reprehenderit sapiente a culpa. Hic impedit natus maxime beatae, mollitia necessitatibus? Numquam, molestias! Eum, eos laudantium. Non dolorem commodi expedita veritatis reprehenderit aperiam quaerat maxime doloremque pariatur beatae, eveniet ipsam! Laboriosam illum ullam et amet repudiandae officiis? Quod deserunt ex iure iste incidunt ab eos consequuntur!
            Fuga facere quam at quibusdam eligendi aut consequuntur maiores consectetur sequi dolore nihil, natus veniam iure sunt enim neque. Qui temporibus vero et quasi maiores fugit soluta doloribus quae! Molestias. Similique possimus sequi blanditiis corrupti deserunt ut illo cum distinctio, minus architecto dolorem tempore libero minima amet porro, assumenda nulla beatae alias maiores eligendi exercitationem reprehenderit. Atque nobis voluptatibus numquam.
            Qui officiis fugiat accusamus illum, aut nam reprehenderit iure, quas aspernatur laudantium labore voluptates unde corrupti? Esse laboriosam officia, quia et reprehenderit inventore, magnam obcaecati qui iure eos aperiam suscipit? Adipisci corrupti quas repellat earum voluptas dicta eveniet at amet saepe error? Vel repellendus natus animi ex dicta ipsa, totam accusamus molestias quam pariatur esse eligendi error minima ut voluptatibus!
            Deserunt dolorem modi possimus blanditiis magni vitae soluta repudiandae molestiae, aspernatur eius velit quasi nulla iusto ab quam optio eaque mollitia iure enim, aut consectetur id? Ipsum suscipit et itaque. Adipisci aspernatur sed aliquid quibusdam voluptate illo dolorum, doloremque quia dignissimos earum laborum, delectus aliquam rem nostrum laboriosam. Accusantium eveniet ipsa velit a itaque eos, reiciendis aperiam culpa quis consequatur.
            Ducimus, omnis ab amet vitae harum expedita fugit atque maiores ex totam reiciendis eius iste obcaecati. Tempora, dolor culpa. Nesciunt, sequi modi? Error natus repudiandae sapiente odio reiciendis et perferendis. Doloremque facilis unde soluta nisi praesentium, possimus magnam consectetur, autem, earum quaerat hic tempore. Laudantium distinctio, at omnis nulla, quam atque soluta iure totam facilis eius praesentium quia sit in.
            Nemo doloremque placeat fugit quae! Deleniti hic impedit distinctio nostrum eum ipsa similique dolorum, accusantium optio velit. Odio eaque veritatis tempora corrupti sed, pariatur officiis, fugit, harum eum voluptates quae! Commodi magni impedit et explicabo voluptatum aperiam soluta eos. Dignissimos sed dolorum ab exercitationem nihil, minus aliquid cumque? Magnam voluptas distinctio neque facilis doloremque in enim iusto aliquid totam asperiores.
            Modi pariatur sequi ea ratione quisquam autem itaque, voluptate, omnis quidem in eligendi quas totam sapiente quam vero eius ipsum dignissimos incidunt corrupti perferendis quaerat enim aspernatur delectus! Dolore, delectus. Eligendi eius inventore nulla, amet nesciunt optio corporis fugiat! Possimus, repellendus aperiam exercitationem, deserunt culpa vero voluptatem, eum qui maxime quod sequi fugit. Quidem odio, doloremque totam officia consequuntur non!
            Nostrum, doloremque ipsa. Saepe sequi eligendi obcaecati fugiat tenetur? Excepturi sapiente fuga odio corrupti blanditiis atque, doloribus mollitia vitae eveniet perspiciatis voluptates quia ab sint sunt quasi deleniti dolorum ipsa. Veritatis, eligendi illo? Ipsum aperiam numquam sequi animi tempora esse doloribus sed aut, a quia! In repellat nulla sed magni repudiandae quasi blanditiis sequi architecto dignissimos. Vero illum natus est!
            Dignissimos velit eius nostrum ab voluptates. Sed laudantium eius exercitationem iusto. Accusantium voluptates ratione expedita id pariatur qui quis iusto eos nesciunt suscipit quam, vitae minus animi quod temporibus maxime! Nostrum corporis suscipit repellendus quo, ut nobis, corrupti accusantium quia expedita, quod quam? Deserunt maxime atque ipsa? Omnis ad nesciunt culpa ut, commodi fuga repudiandae nobis harum eaque, animi et.
            Molestiae id commodi dolor rem quas provident ipsam culpa totam reprehenderit aperiam. Magni, voluptatem? Rem minima, deserunt provident, eum nihil adipisci quae voluptate quibusdam perferendis, velit blanditiis incidunt inve necessitatibus. Quo blanditiis voluptas sit! Similique, dignissimos nesciunt aliquid cumque magni veniam voluptates explicabo voluptatum ullam beatae fuga. Incidunt blanditiis veritatis amet. Hic laudantium asperiores corporis, blanditiis assumenda eos quia illum.
            Deleniti temporibus voluptates sequi dolorem asperiores. Repellat voluptas doloribus explicabo nam, aperiam quos quibusdam labore non ipsa voluptatem et, natus nobis pariatur eaque eos id dolor nulla unde optio porro? Quisquam blanditiis ea, aperiam pariatur quaerat placeat labore, debitis deserunt sequi est quasi maiores quidem ipsam laboriosam atque nobis veniam tempora dolor exercitationem temporibus! Voluptas consequuntur eum repellat commodi adipisci?
            At sunt mollitia aliquid impedit ipsam sit velit rerum necessitatibus excepturi quibusdam! Ducimus ipsam quam minima possimus, at inventore minus. Dolorem, eius numquam? Id distinctio consectetur, similique voluptatibus iure odio. Ad dolores ducimus quaerat beatae! Fugiat minus tenetur, distinctio placeat tempore voluptatem, maxime est at, quasi illum harum natus quo iusto error corporis fuga veritatis cumque! Cumque commodi nihil sapiente?
            Ullam, blanditiis perferendis? Cum fuga suscipit optio. Aperiam laborum minima repellat, doloribus placeat atque officia quos dolore ut a molestiae illum, corrupti minus cumque alias reprehenderit? Minus explicabo magnam quod. Perspiciatis, soluta cum velit fuga corrupti obcaecati atque aut odit blanditiis consequuntur eius, culpa optio debitis eum! Ex, ipsam repudiandae. Qui eius porro odio sit omnis quae ut? Iure, distinctio.
            Dolore omnis, saepe totam voluptate eius doloribus magnam cumque et exercitationem perspiciatis vero neque ipsam, voluptatem dolorem rem odio quae fuga sequi deserunt! Dolorem ipsam mollitia at quas fugit et! Voluptates, assumenda. Ea facilis, sapiente, assumenda doloribus sed fugiat quis eaque amet labore voluptatem fugit reiciendis asperiores. Aperiam, voluptatibus? Repellendus aspernatur corporis earum neque modi labore incidunt esse similique nihil.
            Accusantium itaque suscipit nisi ut eveniet, quisquam tempore, culpa necessitatibus facere iste quo. Adipisci possimus similique at, accusantium tempore dolore incidunt explicabo assumenda eaque, quaerat et porro cumque repellendus distinctio! Sapiente quaerat ad aut, nisi error quis laboriosam! Eum sed sapiente neque rerum, suscipit enim deserunt quisquam debitis ipsa inventore in necessitatibus, quaerat dolor tenetur consequuntur nulla temporibus laboriosam soluta?
            Fugiat quod, ex vel architecto maxime soluta dolores eveniet molestias magnam? Iusto perferendis illum, quas corporis ad cumque tempore magni accusantium voluptate minus necessitatibus eum aperiam? Excepturi quisquam cumque minima? Temporibus repudiandae perferendis ullam praesentium dignissimos maxime dolore non harum dolores ducimus, delectus amet accusamus dolor eum culpa voluptas dicta pariatur illo eveniet dolorum officia. Maxime iste commodi nisi iure!
            Vitae magnam aliquid illo cupiditate architecto asperiores enim! Quis, qui atque eveniet voluptates sint, dolor excepturi natus pariatur at a maxime accusamus repellendus assumenda commodi tempora maiores eligendi, deleniti itaque. Voluptatibus atque exercitationem nesciunt, numquam, recusandae reprehenderit impedit nostrum, vero distinctio corporis modi? Ipsum alias blanditiis est itaque autem, odio magni. Earum, animi a! Doloremque nihil voluptatibus delectus aut sint?
            Vero obcaecati nemo in quae nobis. Fugiat delectus aut veniam at eius, saepe cupiditate magni in velit sed ad neque. Quibusdam nihil consectetur dignissimos, aliquid quisquam suscipit quae autem error? Rem repudiandae quia aliquid, doloribus voluptatibus voluptas, dolore culpa consectetur esse vero deleniti numquam harum ad exercitationem distinctio voluptatem. Laboriosam itaque tempore iure voluptas autem dolorum minus perferendis fugit sunt?"
        ]
    ];

    $new_post = [];
    foreach ($blog_posts as $post) {
        if($post['slug'] === $slug) {
            $new_post = $post;
        }
    }
    return view('post', [
        "title" => "Single Post",
        "post" => $new_post
    ]);
});
